services:
  backend:
    build:
      context: backend/
    ports:
      - "8000:8000"
    volumes:
      - ./backend/cpp/data/silo-10rows.csv:/app/silo.csv:ro
    environment:
      FRONTEND_ORIGIN: "*"


  frontend:
    build:
      context: frontend/
      args:
        NEXT_PUBLIC_API_URL: http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend
